### ISSUE TITLE
naming convention for usgs file causes failure

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#10]
commit id [40b7ddb](https://github.com/CADWRDeltaModeling/dms_datastore/commit/40b7ddb4a68c53cf8eb2bcc3b00e1a541063649c)

### Description

* minor side issue usgs_meta.py needs argparse to specify the directory
* Ran python usgs_meta.py

### What I Did

```
Traceback (most recent call last):
  File "E:\dms_datastore\usgs_meta.py", line 246, in <module>
    main()
  File "E:\dms_datastore\usgs_meta.py", line 241, in main
    process_multivariate_usgs("formatted",pat="usgs*.csv",rescan=True)
  File "E:\dms_datastore\usgs_meta.py", line 140, in process_multivariate_usgs
    df = usgs_multivariate(pat,'usgs_subloc_meta_new.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\dms_datastore\usgs_meta.py", line 86, in usgs_multivariate
    meta = interpret_fname(fname)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\dev\dms_datastore\dms_datastore\filename.py", line 57, in interpret_fname
    raise ValueError(f"Naming convention not matched for {fname}")
ValueError: Naming convention not matched for usgs_c16_380356122023701_ec.csv
```

**Comment by dwr-psandhu** [comment]
Cannot reproduce. Looks like it is fixed
